export const FETCH_FORM = "FETCH_FORM";
export const FETCH_FORM_SUCCESS = "FETCH_FORM_SUCCESS";
export const FETCH_FORM_FAILURE = "FETCH_FORM_FAILURE";
export const FETCH_FORM_WITH_CONTEXT = "FETCH_FORM_WITH_CONTEXT";


export const SUBMIT = "SUBMIT";
export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS";
export const SUBMIT_FAILURE = "SUBMIT_FAILURE";


export const SUBMIT_TO_WORKFLOW = "SUBMIT_TO_WORKFLOW";
export const SUBMIT_TO_WORKFLOW_SUCCESS = "SUBMIT_TO_WORKFLOW_SUCCESS";
export const SUBMIT_TO_WORKFLOW_FAILURE = "SUBMIT_TO_WORKFLOW_FAILURE";

export const RESET_FORM = "RESET_FORM";