export const FETCH_PROCESS_DEFINITIONS = "FETCH_PROCESS_DEFINITIONS";
export const FETCH_PROCESS_DEFINITIONS_SUCCESS = "FETCH_PROCESS_DEFINITIONS_SUCCESS";
export const FETCH_PROCESS_DEFINITIONS_FAILURE = "FETCH_PROCESS_DEFINITIONS_FAILURE";


export const FETCH_PROCESS_DEFINITION = "FETCH_PROCESS_DEFINITION";
export const FETCH_PROCESS_DEFINITION_SUCCESS = "FETCH_PROCESS_DEFINITION_SUCCESS";
export const FETCH_PROCESS_DEFINITION_FAILURE = "FETCH_PROCESS_DEFINITION_FAILURE";


export const RESET = "RESET";